auth:
  internal:
    base-url: http://localhost:8081
    token: DEV_INTERNAL_TOKEN_1234567890

spring:
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
        options:
          model: "gemini-2.5-flash-lite"
          temperature: 0.0
        completions-path: "/chat/completions"
        client:
          connect-timeout: 10s
          read-timeout: 60s
  main:
    web-application-type: servlet
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/hit?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: hit
    password: hradar
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update   # create-drop, create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      notification: hr.notification


jwt:
  secret-key: Q8b83bmIq4KI2lvE+bViXYvo9SyODg1g0Q0dPyG9VNutj0GgBG8SxhWwL3oexDlWtq5uxFZs+k+NWXHYXKLjYg==
  expiration: 3600000  # 1시간
  refresh-expiration: 1209600000 # 2주

server:
  port: 8082

file:
  storage:
    type: s3  # local, s3
  local:
    base-dir: uploads
    base-url: http://localhost:8082/files
  s3:
    bucket: s3-hradar-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    prefix: test/
    base-url: https://s3.ap-northeast-2.amazonaws.com/s3-hradar-bucket/test/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
#
#logging:
#  level:
#    root: INFO
#    org.hit.hradar: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

external:
  vector-index:
    base-url: ${VECTOR_INDEX_BASE_URL}
    timeout:
      connect: 3s
      read: 10s

