spring:
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com/v1beta/openai/"
        options:
          model: "gemini-2.5-flash-lite"
          temperature: 0.0
        completions-path: "/chat/completions"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  config:
    import:
      - classpath:config/kafka.yml

app:
  application:
    name: hr-service

management:
  endpoints:
    web:
      exposure:
        include: health,info