apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-common-config
  namespace: hr-system
data:
  SPRING_PROFILES_ACTIVE: prod
  APP_ENV: prod
  APP_NAME: "HRadar Chatbot"
  VECTOR_INDEX_BASE_URL: "http://hr-chatbot:80"
  AUTH_INTERNAL_BASE_URL: "http://hr-auth:80"
  S3_BUCKET: "s3-hradar-bucket"
  S3_REGION: "ap-northeast-2"
  S3_PREFIX: "prod/"
  KAFKA_TOPIC_CHATBOT: "document.index"
  KAFKA_GROUP_ID_CHATBOT: "hr-chatbot-indexer"
  KAFKA_TOPIC_NOTIFICATION: "hr.notification"
  KAFKA_GROUP_ID_NOTIFICATION: "notification-group"
  CORS_ALLOWED_ORIGINS: "https://hradar.link"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  REDIS_HOST: "hradar-cache-ro.8um4gz.ng.0001.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka-headless.hr-system.svc.cluster.local:9092"
  QDRANT_HOST: "qdrant"
  QDRANT_PORT: "6333"
  QDRANT_COLLECTION: "hradar_docs"
  RELEVANCE_THRESHOLD: "0.45"
  MONGO_CHAT_LOG_COLLECTION: "chat_logs"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
