apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-gateway
  namespace: hr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-gateway
  template:
    metadata:
      labels:
        app: hr-gateway
    spec:
      containers:
        - name: hr-gateway
          image: 850995576970.dkr.ecr.ap-northeast-2.amazonaws.com/hradar-gateway:dc9c4add2978fb9eaffd79285dba1aabab256467
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hr-common-config
            - secretRef:
                name: hr-secrets
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: hr-gateway
  namespace: hr-system
spec:
  type: NodePort
  selector:
    app: hr-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
