apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-notification
  namespace: hr-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-notification
  template:
    metadata:
      labels:
        app: hr-notification
    spec:
      containers:
        - name: hr-notification
          image: 850995576970.dkr.ecr.ap-northeast-2.amazonaws.com/hradar-notification:35e02d9efd841d0eb10f9cd1a3aca0570d2e5d2b
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hr-common-config
            - secretRef:
                name: hr-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: hr-notification
  namespace: hr-system
spec:
  type: NodePort
  selector:
    app: hr-notification
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
