apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hr-project
  source:
    repoURL: https://github.com/Human-Intelligence-Team/HIT-HRadar-Infra.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hr-system
  syncPolicy:
    automated:
      prune: true      # Automatically delete resources that are no longer in Git
      selfHeal: true   # Automatically revert manual changes in the cluster
    syncOptions:
      - CreateNamespace=true  # Create the namespace if it doesn't exist
      - ApplyOutOfSyncOnly=true
